Update versions to latest
fyne-io/fyne-cross-images pull request #41
Opened 2023-12-27 07:24 UTC by lorypelli

Let me know if you want something to not be updated, but I think it's better to update everything...

2023-12-27 08:03 UTC, Jacalz commented
Have you built the images locally and verified that they work?

2023-12-27 08:13 UTC, lorypelli commented
> Have you built the images locally and verified that they work?

I'm having troubles make go running locally, I don't know why it doesn't want to set the PATH on linux

2023-12-27 08:44 UTC, lorypelli commented
> Have you built the images locally and verified that they work?

I need to change sha256

2023-12-27 08:52 UTC, Jacalz commented
You should not knowingly open a PR with untested changes. That's very bad practice

2023-12-27 09:03 UTC, lorypelli commented
> You should not knowingly open a PR with untested changes. That's very bad practice. If something is work in progress, at least open as a draft

Now I managed to test

2023-12-27 09:10 UTC, lorypelli commented
@Jacalz building works correctly

2023-12-27 09:37 UTC, Bluebugs commented
I would prefer one pr for each change and with a descriptive change in each case (like 'updating fyne to v2.4.3')

2023-12-27 10:13 UTC, andydotxyz requested changes
Thanks for this, but watch you don't remove important content.

Has this combination of versions worked well for you?

2023-12-27 10:13 UTC, andydotxyz commented on base/Dockerfile
> -# dev version of Zig to support windows-386 target
This looks like an important comment, please don't remove it

2023-12-27 10:15 UTC, andydotxyz commented
> I would prefer one pr for each change and with a descriptive change in each case (like 'updating fyne to v2.4.3')

Surely that is a lot of overhead for version bumps. If you really need it a separate commit for each managed project, but not a whole PR?

2023-12-27 10:42 UTC, lorypelli commented
> Thanks for this, but watch you don't remove important content.
> 
> Has this combination of versions worked well for you?

I would like to update also zig version but I wasn't able to find sha256, so I restored it to dev, but I didn't add bacl the comment, I will try to find the sha but now I don't have time...

2023-12-27 10:45 UTC, lorypelli commented
I added the comment back for now, you can merge it if you want it builds correctly

2023-12-27 10:48 UTC, lorypelli commented
Actually, I wasn't able to run any command inside of the docker container, it wasn't giving output of them, idk why so I recommend you test this locally by yourself

2023-12-27 10:54 UTC, lorypelli commented
I was able to find it

2023-12-27 11:13 UTC, lorypelli commented on base/Dockerfile
> -# dev version of Zig to support windows-386 target
I was able to update zig version also

2023-12-27 11:38 UTC, Bluebugs commented
Updating zig is a high risk operation. Have you tried to build a few application with this new image using fyne-cross and tested them on their target environment.

2023-12-27 12:08 UTC, lorypelli commented
> Updating zig is a high risk operation. Have you tried to build a few application with this new image using fyne-cross and tested them on their target environment.

If you think it can be an issue, let me know and I will revert the change and make another pull request when I will be able to make sure everything works with it

2023-12-27 12:11 UTC, lorypelli commented
ok, for now I reverted it, let me know if you are able to do some tests with it

2023-12-27 12:11 UTC, Jacalz commented
> > I would prefer one pr for each change and with a descriptive change in each case (like 'updating fyne to v2.4.3')
> 
> Surely that is a lot of overhead for version bumps. If you really need it a separate commit for each managed project, but not a whole PR?
> 

I agree. One commit for each would be more sensible.

2023-12-30 20:51 UTC, andydotxyz commented
> @[lorypelli](https://github.com/lorypelli) lorypelli requested a review from [andydotxyz](https://github.com/andydotxyz) [3 days ago](https://github.com/fyne-io/fyne-cross-images/pull/41#event-11344807016)

I'm not the right person to review this - but others are around who know it well.

2024-04-03 21:18 UTC, Jacalz commented
Sorry @lorypelli, I think this got superseded by https://github.com/fyne-io/fyne-cross-images/pull/43. Apologies.

2024-04-03 21:18 UTC, closed without merging

2024-04-03 21:19 UTC, Jacalz commented
I closed this now but you are more than welcome to open a new PR for that workflow misspelling. I don't think there is any need to update fixuid because the latest release of fyne-cross doesn't use it as far as I know.