Image updates - maintenance release
fyne-io/fyne-cross-images pull request #55
Opened 2024-12-28 09:39 UTC by lucor

This PR provides a maintenance release for the docker images.

> Note requires fyne-cross 1.6.0

## base image:
- update to debian bookworm #49 
- update Go to v1.23.4 #54 
- improve Wayland support #45 
- verify Zig archives using minisign
## darwin image
- verify Zig archives using minisign
> Note: this is the only image that need to use Zig v0.9.1 to cross compile. See https://github.com/ziglang/zig/issues/20689. Also we need to note that we are able to support only MacOS SDK 11.3
Relates to #46 
## darwin-sdk-extractor
- update `build.zig` to support Zig 0.13.0 syntax
## freebsd
- update to support FreeBSD 14.2
- update LLVM to v17 #47

2025-01-02 16:27 UTC, Jacalz commented
Last time I was testing non-released fyne-cross images I had some trouble. What is the best way to force fyne-cross into using these?

2025-01-02 20:33 UTC, lucor commented
Probably the best way is to checkout the PR branch and build the images locally, then fyne-cross should use the local images.

Noticed the CI failures, I'll have a look at them.

2025-01-12 14:15 UTC, andydotxyz commented on freebsd/amd64/Dockerfile
> +    #bsdtar -C /freebsd /tmp/download/All/*.pkg; \
This looks a bit peculiar - was it an accident or should it be removed?

2025-01-12 16:57 UTC, Jacalz commented
I suppose that an update to the fyne-cross command should make the web CI work?

2025-01-12 17:17 UTC, Jacalz requested changes
We have to get the web image updated as it is currently installing Go 1.17 (which does not compile with Fyne any more) and it does install GopherJS which we no longer support. We have to get the web image update

2025-01-12 17:20 UTC, Jacalz commented
I can't get my Fedora Silverblue 41 installation to use the locally built images; it just pulls the latest tagged once when I try to use it. Anyway, images built fine :)

2025-01-13 19:18 UTC, lucor commented on freebsd/amd64/Dockerfile
> +    #bsdtar -C /freebsd /tmp/download/All/*.pkg; \
Thanks for catching, it was not used code left behind during cleanup.
Fixed in [c58fd2a](https://github.com/fyne-io/fyne-cross-images/pull/55/commits/c58fd2af01a650b64baf6c30d5eb27b668cd6a5c)

2025-01-13 19:21 UTC, lucor commented
> We have to get the web image updated as it is currently installing Go 1.17 (which does not compile with Fyne any more) and it does install GopherJS which we no longer support. We have to get the web image update

Indeed, was waiting for the fyne-cross updates :) 
Fixed in [2506c71](https://github.com/fyne-io/fyne-cross-images/pull/55/commits/2506c71f6f942c0a51f043fabdd5d23c1fd8ff8e). The web image is now a tag to the base one.

2025-01-13 19:51 UTC, lucor commented
> I can't get my Fedora Silverblue 41 installation to use the locally built images; it just pulls the latest tagged once when I try to use it. Anyway, images built fine :)
> 
That is unfortunate :(, we should investigate that. Anyway in the maintime, a `dev-<image-name>` (i.e. `dev-linux`) should be tagged locally and can be used via `--image` tag

Happy to hear all images built correctly :)

2025-01-13 19:58 UTC, lucor commented
CI is happy now with the required fyne-cross 2.6.1@develop https://github.com/fyne-io/fyne-cross/pull/289.
Once the new version of fyne-cross is released, we need to update the version in this PR

2025-01-15 02:51 UTC, Bluebugs approved these changes

2025-01-19 14:57 UTC, andydotxyz commented
Good plan, maybe the release can land later today and all of this can come together :)

2025-01-19 20:06 UTC, Bluebugs approved these changes

2025-01-19 20:14 UTC, merged

2025-01-19 20:17 UTC, lucor commented
Ready for the release :tada: 
Thanks all for feedback and testing!
@Bluebugs the CI feature for the arm64 host support landed just in time to catch a last minute release bug :)